### ISSUE TITLE
old Entities still being recalled 

### ISSUE THREAD

**Issue by LazzaAU** [nikpoz/Home-assistant-Snips.ai-via-Node-Red#1]
Hi There. pretty sure this is more of a snips issue than your app but thought id ask here as you may be able to help.

Ive added my own entity names and deleted yours and then re trained my assistant. However every now and then i get your entity_id's showing up in the payload despite your examples not  being there anymore 

Example, 

In lightturnon1 slot i have a entity name called insideTemp and synomyns of Inside temperature, inside

Training examples are done and assistant has been reloaded to my snips platform.

When asking snips "whats the inside temperature", snips recognises my intent as per screen shot 
![inside temp](https://user-images.githubusercontent.com/31381872/62402810-e0bdc600-b5cc-11e9-84c2-83ea0c33d9b6.PNG)

but the actual payload gets delivered with your entity_id of 

> data: object
entity_id: "light.secret_led_two" 

and not insideTemp as expected.

Any tips on cleaning that up at all please ?

PS: I know this isn't a on / off switch.... I have created a addition to your node red flow which takes the entity id from your seperation block, changes the payload and sends it via MQTT to another flow i have

Thanks for any feedback

**Comment by nikpoz** [comment]
Hi LazzaWA
secret_led_two appears cause snips does not push a proper value to the flow. In the flow secret_led_two is set as the temporary value in the "value extraction" node ,where the msg.topic is set to a new json. That is the reason it appears.
If after the seperation node secret_led_two still appears in your debug message, the seperation did not work. So firstly make sure that the sensor name in the seperation node is inserted correctly and as a string value（inside_temperature）.
 Check again and see if this fixes this issue.

**Comment by nikpoz** [comment]
Hi LazzaWA
secret_led_two appears cause the flow  uses it as  a  base value.
In the flow secret_led_two is set as the temporary value in the "value extraction" node ,where the msg.topic is set to a new json （first rule）. That is the reason it appears.
Nothing wrong there, the flow functions as expected. 
It is the seperation node that did not work. So firstly make sure that the sensor name in the seperation node, is inserted correctly and as a string value（replace with inside_temperature the value of insideTemp in your seperation node ）.
Check again and see if this fixes this issue.
If snips pushes an other value（synonym） just grab it an place it the seperation.
You have such flexibility...
secret_led_two will appear on debug messages before the
seperation node,  its not assistant's issue. It is replaced with the value gained
 from the assistant in the same node and you can set it practically to anything , 
if you edit the set msg.topic rule in the value extraction node （try to change "secret_led_two" with something like "temp_id" in this rule to help you erase the old name） 
Regarding  snips pushing a synonym as a slot value,
 I cannot guess why this happens... its clearly snips app.

**Comment by LazzaAU** [comment]
thanks for that. yes your right, one of my problems was i was missing " _ " in the separation value. that sorted that part of the problem out. However i still have your entitiy id's showing up in "sam watch" despite them not in the console/assistant any more. i will investigate further on that. thanks

**Comment by nikpoz** [comment]
Thanks for pointing out this.
 It is a bit confusing to see it in the debug msgs.
It will be fixed in the upcoming update.
